add implementated network metrices
san-projekt/projekt pull request #15
Opened 2023-12-04 14:05 UTC by 7ben18

- implementierung der Netzwerk Metriken: Degree, Closeness, Betweenness + Verlauf der Metriken ueber Episode. (Bar und Lineplot)

2023-12-04 14:50 UTC, patschue requested changes
Kapitel 4:
- Linienplots statt Barplots, finde diesen Barplot zu unübersichtlich, besonders welcher Bar zu welcher Episode gehört. Der letzte Linienplot gefällt mir gut.
- TC-14 entfernen. Es hat nur Werte für eine Episode. Evtl. gibt es einen anderen Charakter, der häufiger vorkommt.

Kapitel 5:
- Auch hier, ich finde den Linienplot viel leserlicher.

2023-12-04 18:01 UTC, 7ben18 commented
> Kapitel 4:
> 
> * Linienplots statt Barplots, finde diesen Barplot zu unübersichtlich, besonders welcher Bar zu welcher Episode gehört. Der letzte Linienplot gefällt mir gut.
> * TC-14 entfernen. Es hat nur Werte für eine Episode. Evtl. gibt es einen anderen Charakter, der häufiger vorkommt.


Finde Linienplots ebenfalls übersichtlicher, jedoch kann es sein, das ein Charakter am Anfang und Ende vorkommt aber dazwischen nicht, dann würde es uns eine komplette Linie durch den Plot ziehen (Was ja falsch wäre) 
Siehe Beispiel Plots mit ANAKIN Charakter:
![image](https://github.com/san-projekt/projekt/assets/66916399/f683474b-2168-4f7c-9920-6294d36cd750)
![image](https://github.com/san-projekt/projekt/assets/66916399/ec3cd02a-7318-4cac-913c-40330fd78cc7)

Mein Vorschlag: Da wir mit Diskreten Variabeln arbeiten (Episoden) -> Beides drinnen lassen fürs erste (Funktion ermöglicht uns einfach zwischen "bar" und "line" zu wechseln. 
Google Recherche: Scatterplot oder Boxplots. (Boxplot fällt aber aus, da keine Verteilung)
Evtl noch Disskussionbedarf :) (https://www.data-to-viz.com/#sankey)

> Kapitel 5:
> 
> * Auch hier, ich finde den Linienplot viel leserlicher.

![image](https://github.com/san-projekt/projekt/assets/66916399/4e391379-03df-4ae3-9fba-4cb30c21177c)
Evtl doch wechseln auf Scatterplot

2023-12-05 09:56 UTC, patschue approved these changes

2023-12-05 10:04 UTC, patschue commented
lgtm

2023-12-05 14:08 UTC, merged